AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Execute Lambda for more than 15 minutes without Step Functions

Globals:
  Function:
    Timeout: 30
Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: lambda-role
      AssumeRolePolicyDocument:
        Statement:
          - Action:
            - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaExecute
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::aws:policy/AmazonKinesisFullAccess

Resources:
  StateFunction:
    Type: AWS::Serverless::Function
    DependsOn: LambdaRole
    Properties:
      Role: 'arn:aws:iam::${AWS::AccountId}:role/lambda-role'
      CodeUri: state_function/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        StateFunction:
          Type: Api
          Properties:
            Path: /
            Method: get

Outputs:
  StateFunctionApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"


Metadata:
  AWS::ServerlessRepo::Application:
    Name: state-app
    Description: Execute Lambda for more than 15 minutes without Step Functions
    Author: Sparsh Goyal
